apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-analyzer-backend
  namespace: default
  labels:
    app: portfolio-analyzer-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-analyzer-backend
  template:
    metadata:
      labels:
        app: portfolio-analyzer-backend
    spec:
      containers:
      - name: portfolio-analyzer-backend
        image: ghcr.io/subasico/portfolioanalyzerbackend:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "False"
        - name: API_PREFIX
          value: "/api/v1"
        - name: ALLOWED_ORIGINS
          value: "https://allaboutai.com,https://www.allaboutai.com"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: portfolio-analyzer-secrets
              key: database-url
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-analyzer-secrets
              key: anthropic-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-analyzer-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-analyzer-secrets
              key: anthropic-api-key
              optional: true
        - name: LLM_PROVIDER
          value: "openai"
        - name: LLM_MODEL
          value: "gpt-4o"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-analyzer-backend-service
  namespace: default
  labels:
    app: portfolio-analyzer-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: portfolio-analyzer-backend
