name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACR_NAME: YOUR_ACR_NAME
  IMAGE_NAME: portfolio-analyzer-backend
  AKS_CLUSTER_NAME: YOUR_AKS_CLUSTER_NAME
  AKS_RESOURCE_GROUP: YOUR_RESOURCE_GROUP
  NAMESPACE: default

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}

    - name: Create namespace if not exists
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml -n ${{ env.NAMESPACE }}
        kubectl apply -f k8s/ingress.yaml -n ${{ env.NAMESPACE }}
        kubectl apply -f k8s/hpa.yaml -n ${{ env.NAMESPACE }}

    - name: Restart deployment
      run: |
        kubectl rollout restart deployment/portfolio-analyzer-backend -n ${{ env.NAMESPACE }}
        kubectl rollout status deployment/portfolio-analyzer-backend -n ${{ env.NAMESPACE }} --timeout=5m

    - name: Get deployment status
      run: |
        kubectl get pods -n ${{ env.NAMESPACE }} -l app=portfolio-analyzer-backend
        kubectl get svc -n ${{ env.NAMESPACE }} -l app=portfolio-analyzer-backend
        kubectl get ingress -n ${{ env.NAMESPACE }}

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx

    - name: Run tests
      run: |
        echo "Add your tests here"
        # pytest tests/
